// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "trow2");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "tus2");
user_pref("app.normandy.startupExperimentPrefs.privacy.annotate_channels.strict_list.enabled", true);
user_pref("app.normandy.startupExperimentPrefs.urlclassifier.trackingAnnotationTable.testEntries", "etp-experiment-1.dummytracker.org");
user_pref("app.normandy.user_id", "1602d62b-f72b-5f4d-8803-af862a569098");
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1594124374);
user_pref("app.update.lastUpdateTime.background-update-timer", 1594124174);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1594123686);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1594123928);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1594124146);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1594123806);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1594124294);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1594123716);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1594124494);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 28056);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1594123656);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{84004f26-fc86-b244-9d65-019bc2261911}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1594123687351");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1594125465351");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1594123662114");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1594127262114");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200630195452");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 1423);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200630195452");
user_pref("browser.startup.homepage_override.mstone", "78.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1594124802);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1594123658702");
user_pref("devtools.debugger.pending-selected-location", "{\"sourceId\":\"sourceURL-http://localhost:12345/2CyNTtFfs!s!iso-8859-1/http://localhost:5000/push.js\",\"line\":94,\"column\":4,\"sourceUrl\":\"\",\"url\":\"http://localhost:12345/2CyNTtFfs!s!iso-8859-1/http://localhost:5000/push.js\"}");
user_pref("devtools.debugger.prefs-schema-version", 11);
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "78.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.testing.ignorePermission", true);
user_pref("dom.push.userAgentID", "6a0f4d925c28453fb75e25e1adcdf629");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1594124375);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200630195452");
user_pref("extensions.lastAppVersion", "78.0.1");
user_pref("extensions.lastPlatformVersion", "78.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f115427a-7102-f84f-8618-e29680a44787\",\"formautofill@mozilla.org\":\"3e4dd8c1-a9cb-554a-8451-3b8956527da2\",\"screenshots@mozilla.org\":\"66a5dbdd-ea49-5345-bed1-657b0ddbd6db\",\"webcompat-reporter@mozilla.org\":\"96d361b2-a359-ff45-8439-22a0fa91efff\",\"webcompat@mozilla.org\":\"e77f8b05-5155-cc4e-a672-4bcb47b8cd24\",\"default-theme@mozilla.org\":\"dafea455-5ea5-ef48-9358-eff17d987c47\",\"google@search.mozilla.org\":\"4e7a2822-0b3e-3541-85a6-89385d6ebe87\",\"amazondotcom@search.mozilla.org\":\"7d056c34-93b3-6a4a-9804-ad14f6804797\",\"bing@search.mozilla.org\":\"1a231ea5-c07b-7c48-a20c-9015a9ebb966\",\"ddg@search.mozilla.org\":\"dea6cf6e-0583-fd47-b64c-d2a2fa375940\",\"ebay@search.mozilla.org\":\"47a7d7fc-1402-8547-95a5-344534d3cc11\",\"twitter@search.mozilla.org\":\"b96fdf35-1726-9445-98b1-7fae53fa4851\",\"wikipedia@search.mozilla.org\":\"535d89c9-4972-884f-b042-c30835ca8dd7\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("ignorePermission", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("notification.prompt.testing", true);
user_pref("notification.prompt.testing.allow", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ea145204-9bb4-be4c-b91c-f2fea563fbbd");
user_pref("security.sandbox.plugin.tempDirSuffix", "7b9233da-90e4-1445-8523-528f88b61d9c");
user_pref("services.settings.clock_skew_seconds", -7);
user_pref("services.settings.last_update_seconds", 1594124300);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1594124800);
user_pref("toolkit.telemetry.cachedClientID", "bb098d55-d277-d945-9ea5-a02be78e3849");
user_pref("toolkit.telemetry.previousBuildID", "20200630195452");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
